/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

SynthAudioProcessor::SynthAudioProcessor()
{
	UserParams[MasterBypass] = 0.0f;//default to not bypassed
	//repeat for "OtherParams":

	synths.push_back(&sineSynth);
	synths.push_back(&triangleSynth);
	synths.push_back(&squareSynth);
	synths.push_back(&sawtoothSynth);

	sineSynth.addSound(new SynthSound());
	for (int i = 0; i < 8; i++) {
		sineSynth.addVoice(new SineVoice());
	}

	triangleSynth.addSound(new SynthSound());
	for (int i = 0; i < 8; i++) {
		triangleSynth.addVoice(new TriangleVoice());
	}

	squareSynth.addSound(new SynthSound());
	for (int i = 0; i < 8; i++) {
		squareSynth.addVoice(new SquareVoice());
	}

	sawtoothSynth.addSound(new SynthSound());
	for (int i = 0; i < 8; i++) {
		sawtoothSynth.addVoice(new SawtoothVoice());
	}

	// default sound: no sound
	currentSynthP = nullptr;

	// target level:
	gain = 1.0;

	// start level:
	currentGain = 0.0;

	// attack in milliseconds:
	attackMS = 2000;

	// samples = ms * samplerate(48,0)
	attackSamples = attackMS * 48;

	// gain-plus per sample:
	gainDelta = gain / attackSamples;
	
	consoleChanged = false;

	log("attackMS: " + std::to_string(attackMS));

}

SynthAudioProcessor::~SynthAudioProcessor() {
	//delete currentSynthP;
}

//==============================================================================
const String SynthAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

int SynthAudioProcessor::getNumParameters() {
	return totalNumParam;
}

float SynthAudioProcessor::getParameter(int index) {
	switch (index) {
	case waveFormParam:
		return waveForm;
	default:
		return 0.0f;
	}
}

void SynthAudioProcessor::setParameter(int index, float newValue) {
	switch (index) {
	case waveFormParam:
		waveForm = newValue;
		break;
	default:
		UserParams[waveFormParam] = 0;
		break;
	}
}

const String SynthAudioProcessor::getParameterName(int index) {
	switch (index) {
	case waveFormParam:
		return "WaveForm";
	default:
		return String::empty;
	}
}

const String SynthAudioProcessor::getParameterText(int index) {
	switch (index) {
	case waveFormParam:
		return String(UserParams[waveFormParam]);
	default:
		return String::empty;
	}
}

const String SynthAudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String SynthAudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool SynthAudioProcessor::isInputChannelStereoPair (int index) const
{
    return true;
}

bool SynthAudioProcessor::isOutputChannelStereoPair (int index) const
{
    return true;
}

bool SynthAudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool SynthAudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool SynthAudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double SynthAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int SynthAudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int SynthAudioProcessor::getCurrentProgram()
{
    return 0;
}

void SynthAudioProcessor::setCurrentProgram (int index)
{
}

const String SynthAudioProcessor::getProgramName (int index)
{
    return String();
}

void SynthAudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void SynthAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
}

void SynthAudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void SynthAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    // In case we have more outputs than inputs, this code clears any output
    // channels that didn't contain input data, (because these aren't
    // guaranteed to be empty - they may contain garbage).
    // I've added this to avoid people getting screaming feedback
    // when they first compile the plugin, but obviously you don't need to
    // this code if your algorithm already fills all the output channels.
    for (int i = getNumInputChannels(); i < getNumOutputChannels(); ++i)
        buffer.clear (i, 0, buffer.getNumSamples());

    // This is the place where you'd normally do the guts of your plugin's
    // audio processing...
    for (int channel = 0; channel < getNumInputChannels(); ++channel)
    {
        float* channelData = buffer.getWritePointer (channel);

        // ..do something to the data...
    }

	// get current synth:
	
	if (waveForm >= 0) {

		currentSynthP = synths.at(waveForm);

		currentSynthP->renderNextBlock(buffer, midiMessages, 0, buffer.getNumSamples());
		for (int i = 0; i < currentSynthP->getNumVoices(); i++) {
			if (sineSynth.getVoice(i)->isVoiceActive()) {
				if (currentGain < gain) {
					envelope(buffer);
					log(std::to_string(currentGain));
				}
			}
		}
		
	}

}

//==============================================================================

template <typename FloatType>
void SynthAudioProcessor::envelope(AudioBuffer<FloatType>& buffer) {
	for (int channel = 0; channel < getNumInputChannels(); ++channel) {
		
		// gain-plus per sample:
		gainDelta = gain / attackSamples * buffer.getNumSamples();

		buffer.applyGainRamp(channel, 0, buffer.getNumSamples(), currentGain, (currentGain + gainDelta));
		
		if (currentGain < gain) {
			currentGain = currentGain + gainDelta;
		}
		if (currentGain > gain) {
			currentGain = gain;
		}

	}
}

inline float dB2gain(float dB){
	return pow(10, dB / 20);
}

inline float gain2dB(float gain){
	return 20 * log(gain);
}

void SynthAudioProcessor::log(std::string text) {
	consoleText = text + "\n";
	consoleChanged = true;
}

bool SynthAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* SynthAudioProcessor::createEditor()
{
    return new SynthAudioProcessorEditor (*this);
}

//==============================================================================
void SynthAudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void SynthAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new SynthAudioProcessor();
}
