/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#ifndef PLUGINPROCESSOR_H_INCLUDED
#define PLUGINPROCESSOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "SynthSound.h"
#include "SineVoice.h"
#include "TriangleVoice.h"
#include "SquareVoice.h"
#include "SawtoothVoice.h"
#include <string>
#include <math.h>


//==============================================================================
/**
*/
class SynthAudioProcessor  : public AudioProcessor
{
public:
    //==============================================================================
    SynthAudioProcessor();
    ~SynthAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock (AudioSampleBuffer&, MidiBuffer&) override;

    //==============================================================================
    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==============================================================================
    const String getName() const override;

	int getNumParameters() override;
	float getParameter(int index) override;
	void setParameter(int index, float newValue) override;

	const String getParameterName(int index) override;
	const String getParameterText(int index) override;

    const String getInputChannelName (int channelIndex) const override;
    const String getOutputChannelName (int channelIndex) const override;
    bool isInputChannelStereoPair (int index) const override;
    bool isOutputChannelStereoPair (int index) const override;

    bool acceptsMidi() const override;
    bool producesMidi() const override;
    bool silenceInProducesSilenceOut() const override;
    double getTailLengthSeconds() const override;

    //==============================================================================
    int getNumPrograms() override;
    int getCurrentProgram() override;
    void setCurrentProgram (int index) override;
    const String getProgramName (int index) override;
    void changeProgramName (int index, const String& newName) override;

    //==============================================================================
    void getStateInformation (MemoryBlock& destData) override;
    void setStateInformation (const void* data, int sizeInBytes) override;

	//Custom Methods, Params and Public Data
	enum Parameters {
		MasterBypass = 0,
		waveFormParam = 1,
		attackParam = 2,
		totalNumParam
	};

	void log(std::string text);

	bool consoleChanged;

	int waveForm;
	std::string consoleText;

	int attackMS;

	float gain;
	float currentGain;

private:
    //==============================================================================
	
	//Private Data, helper methods etc.
	float UserParams[totalNumParam];
	bool UIUpdateFlag;

	Synthesiser sineSynth;
	Synthesiser triangleSynth;
	Synthesiser squareSynth;
	Synthesiser sawtoothSynth;

	std::vector<Synthesiser*> synths;

	std::vector<float> currentGains;

	Synthesiser* currentSynthP;

	template <typename FloatType>
	void envelope(float& currentGain, AudioBuffer<FloatType>& buffer);

	JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(SynthAudioProcessor)
};


#endif  // PLUGINPROCESSOR_H_INCLUDED
